name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - run: npm ci
      - run: npm run build --if-present
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_ASSET_URL: ${{ vars.VITE_ASSET_URL }}
          VITE_SECRET_KEY: ${{ secrets.VITE_SECRET_KEY }}
      - run: npm run test
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_ASSET_URL: ${{ vars.VITE_ASSET_URL }}
          VITE_SECRET_KEY: ${{ secrets.VITE_SECRET_KEY }}

