version: "3.7"
services:
  # It is better in theory to host the laravel app in Docker, but from experience
  # requests take much longer compared to when it's hosted locally.
  app:
    container_name: mov-mm-backend
    image: jasonpf/mov-mm-backend:1.1
    environment:
      - APACHE_RUN_USER=#${DOCKER_UID}
      - APACHE_RUN_GROUP=#${DOCKER_UID}
    volumes:
      - ./:/var/www/mov-mm-backend
    working_dir: /var/www/mov-mm-backend/
    ports:
      - ${DOCKER_HOST_PORT}:80
      
  redis:
    image: redis:6.2
    container_name: mov-mm-backend-redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
    - ./redis/redis:/data
    ports:
      - "6382:6379"

  db:
    image: mysql:8.0.23
    restart: always
    container_name: mov-mm-backend-db
    ports:
      - 3333:3306
    environment:
      MYSQL_DATABASE: movingmessage
      MYSQL_USER: mysql
      MYSQL_PASSWORD: Abc123456
      MYSQL_ROOT_PASSWORD: Abc123456
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    #command: -p ${DOCKER_DB_PORT}:3306
    
  db-test:
    image: mysql:8.0.23
    restart: always
    container_name: mov-mm-backend-db-test
    ports:
      - 7777:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    #command: -p ${DOCKER_DB_PORT}:3306